{
 "title": "Trace Explorer Dashboard",
 "tags": [
  "trace",
  "observability",
  "petclinic",
  "zipkin"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "trace_id", "label": "Trace ID", "query": "7a88cb63dd273f2d" }
  ]
 },
 "panels": [
  { "title": "Trace Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Trace Timeline",
   "type": "traces",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "query": "$trace_id" }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Metric Details for Trace: $trace_id",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum / http_server_requests_seconds_count # trace_id=\"$trace_id\"",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "All Logs for Trace: $trace_id",
   "type": "logs",
   "description": "Logs associated with the trace ID",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=~\".+\"}|=\"$trace_id\""
    }
   ]
  }
 ]
}